import type { ModuleDefinition } from "@app/module-sdk";
import Explore from "./Explore";
import { initialState, sanitizeState } from "./state";

const definition: ModuleDefinition = {
  id: "module-20-train-tiny-lm",
  slug: "train-tiny-lm",
  title: "Train one from scratch",
  group: "training-adapting",
  order: 40,
  icon: "Bot",
  accent: "#7a5bc7",
  prerequisites: ["module-18-dataset-building", "module-19-hyperparameters-schedules"],
  estimatedMinutes: 18,
  steps: ["Pick a corpus", "Pick a size", "Train it", "Set the recipe", "Read the model card"],
  stepInstructions: [
    "Choose each of the three corpora in turn and compare how much text each one actually provides.",
    "Move Model size from 1 to 12 and watch the weight count, the solid training curve, and the dashed held-out curve respond.",
    "Raise Epochs and read the three samples A, B, and C, which are marked on the curve: they go from noise to letter clusters to word-shaped text.",
    "On the Training recipe card, raise Learning rate to 4 on Constant, then switch Schedule to Cosine decay and compare Held out. Try rate 8, watch the run halt, and turn Gradient clip up to 0.50. Last, switch Training text to Raw scrape and compare Held out with Footer lines.",
    "Read the model card and compare the training loss with the held-out loss for the size and recipe you chose; the shaded band on the chart is the same gap. Copy my recipe saves every setting as one line of text.",
  ],
  stateVersion: 2,
  tagline:
    "Choose a corpus, a size, and a recipe, then read the finished artifact: real weights, a real held-out score, and samples that improve as the loss falls.",
  objectives: [
    "Assemble the decisions that define a training run: text, size, and recipe",
    "Relate parameter count to how well a model can fit its data",
    "Read a model card and say what it does and does not promise",
    "Set learning rate, schedule, batch size, and gradient clip together, and judge the recipe by held-out loss",
  ],
  glossary: [
    {
      term: "From scratch",
      definition:
        "Starting from initialized weights rather than someone else's trained ones. Everything the model knows has to come from the corpus you chose.",
    },
    {
      term: "Rank",
      definition:
        "The inner dimension of a factorized weight matrix. Here it is the capacity dial: parameters are two times rank times vocabulary.",
    },
    {
      term: "Factorization",
      definition:
        "Storing a large matrix as the product of two thin ones. Cheaper to store and train, and unable to express every matrix the full version could.",
    },
    {
      term: "Capacity",
      definition:
        "How much structure a model can represent at all. Too little and it cannot fit the data; too much and it can fit noise.",
    },
    {
      term: "Underfitting",
      definition:
        "A training loss that stays high because the model cannot represent the data's structure, or has not trained long enough. More capacity fixes the first kind; more steps fix only the second.",
    },
    {
      term: "Overfitting",
      definition:
        "Fitting the training text more closely than text of the same kind that was held out. It shows up as a held-out curve that stops falling, or rises, while the training curve keeps dropping.",
    },
    {
      term: "Held-out loss",
      definition:
        "Cross-entropy on text kept out of training. The gap between it and the training loss is the only honest signal of generalization here.",
    },
    {
      term: "Generalization gap",
      definition:
        "Held-out loss minus training loss. It tends to grow with capacity and with epochs, though on 119 held-out characters it moves unevenly from one setting to the next.",
    },
    {
      term: "Perplexity",
      definition:
        "The exponential of cross-entropy in nats: the number of equally likely options that would leave the model as uncertain. Uniform guessing over 30 symbols scores 30.",
    },
    {
      term: "Model card",
      definition:
        "The record of what was trained on what, with which recipe, and how it scored. It documents scope and limits, not quality.",
    },
    {
      term: "Sample",
      definition:
        "Text generated by repeatedly drawing from the model's next-token distribution. Samples show what the loss number feels like, and are not themselves a measurement.",
    },
    {
      term: "Training recipe",
      definition:
        "Everything about a run apart from the architecture: which text it reads, epochs, peak learning rate, schedule, batch size, gradient clip, and seed. A model card records it so the result can be reproduced.",
    },
    {
      term: "Learning-rate schedule",
      definition:
        "How the step size changes over the run: constant, cosine decay, warmup then decay, or one cycle. The schedule multiplies the peak learning rate, so the best peak depends on the schedule chosen.",
    },
    {
      term: "Gradient clipping",
      definition:
        "Scaling down any batch gradient whose norm exceeds a threshold before the step. It keeps one oversized step from wrecking the weights. When the rate is too large for the whole run it only contains the damage, because every step still overshoots, and it does not make the rate a good one.",
    },
  ],
  references: [
    {
      authors: "Daniel Jurafsky and James H. Martin",
      title: "Speech and Language Processing, 3rd edition draft",
      source: "Stanford University, free to read online",
      year: 2026,
      url: "https://web.stanford.edu/~jurafsky/slp3/",
      note: "The chapter on n-gram language models builds a bigram model, samples text from it, and scores it on a held-out test set. It shows how perplexity follows from cross-entropy and reads it as a branching factor, the same idea as the Model card's Perplexity.",
    },
    {
      authors: "Ian Goodfellow, Yoshua Bengio, and Aaron Courville",
      title: "Deep Learning",
      source: "MIT Press, free to read online",
      year: 2016,
      url: "https://www.deeplearningbook.org/",
      note: "Section 5.2, Capacity, Overfitting and Underfitting, explains the three ideas the Model size sweep shows on screen. Section 7.8, Early Stopping, uses a held-out curve to decide when to stop, as the Proverbs run at rank 12 does.",
    },
    {
      authors: "Katherine Lee, Daphne Ippolito, Andrew Nystrom, et al.",
      title: "Deduplicating Training Data Makes Language Models Better",
      source: "Proceedings of the 60th Annual Meeting of the Association for Computational Linguistics (ACL 2022), 8424–8445",
      year: 2022,
      url: "https://aclanthology.org/2022.acl-long.577/",
      note: "Finds many exact and near-duplicate passages in real training sets. Removing them means models copy less training text and train in fewer steps, and it cuts the train-test overlap that makes held-out scores look better than they are.",
    },
    {
      authors: "Guilherme Penedo, Hynek Kydlíček, Loubna Ben Allal, et al.",
      title: "The FineWeb Datasets: Decanting the Web for the Finest Text Data at Scale",
      source: "Advances in Neural Information Processing Systems 37 (NeurIPS 2024), Datasets and Benchmarks Track",
      year: 2024,
      url: "https://proceedings.neurips.cc/paper_files/paper/2024/hash/370df50ccfdf8bde18f8f9c2d9151bda-Abstract-Datasets_and_Benchmarks_Track.html",
      note: "Documents the filtering and deduplication used to turn 96 Common Crawl snapshots into a 15-trillion-token training set, and tests each choice by training models on the result. It is the full-size version of the Raw scrape versus Cleaned scrape choice.",
    },
    {
      authors: "Ilya Loshchilov and Frank Hutter",
      title: "SGDR: Stochastic Gradient Descent with Warm Restarts",
      source: "International Conference on Learning Representations (ICLR 2017)",
      year: 2017,
      url: "https://arxiv.org/abs/1608.03983",
      note: "Introduces cosine annealing, which lowers the learning rate along a cosine curve, with restarts. The lab's Cosine decay schedule is a single cycle of it with no restart.",
    },
    {
      authors: "Priya Goyal, Piotr Dollár, Ross Girshick, et al.",
      title: "Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour",
      source: "arXiv preprint arXiv:1706.02677",
      year: 2017,
      url: "https://arxiv.org/abs/1706.02677",
      note: "Scales the learning rate along with the batch size and adds a warmup at the start of training to get past the problems large steps cause early on. It backs the Warmup + decay schedule and the lesson's point that batch size and learning rate are chosen together.",
    },
    {
      authors: "Razvan Pascanu, Tomas Mikolov, and Yoshua Bengio",
      title: "On the difficulty of training recurrent neural networks",
      source: "Proceedings of the 30th International Conference on Machine Learning (ICML 2013), PMLR 28(3), 1310–1318",
      year: 2013,
      url: "https://proceedings.mlr.press/v28/pascanu13.html",
      note: "Explains exploding gradients and proposes gradient norm clipping, which rescales a gradient that is too large back to a threshold. That is what the Gradient clip control does when a rate of 8 makes the factored run diverge.",
    },
    {
      authors: "Margaret Mitchell, Simone Wu, Andrew Zaldivar, et al.",
      title: "Model Cards for Model Reporting",
      source: "Proceedings of the Conference on Fairness, Accountability, and Transparency (FAT* 2019), 220–229",
      year: 2019,
      url: "https://arxiv.org/abs/1810.03993",
      note: "The paper that proposed model cards. Its template lists model details, intended use, metrics, evaluation data, and training data, the longer version of the lab's Model card and of the lesson's point that a card states scope, not quality.",
    },
    {
      authors: "Jordan Hoffmann, Sebastian Borgeaud, Arthur Mensch, et al.",
      title: "Training Compute-Optimal Large Language Models",
      source: "Advances in Neural Information Processing Systems 35 (NeurIPS 2022)",
      year: 2022,
      url: "https://proceedings.neurips.cc/paper_files/paper/2022/hash/c1e2faff6f588870935f114ebe04a3e5-Abstract-Conference.html",
      note: "The Chinchilla paper, listed in the proceedings as \"An empirical analysis of compute-optimal large language model training\". It finds that model size and training tokens should grow together, the real-scale finding behind the lesson's warning that smaller-fits-better is conditional.",
    },
    {
      authors: "Diederik P. Kingma and Jimmy Ba",
      title: "Adam: A Method for Stochastic Optimization",
      source: "International Conference on Learning Representations (ICLR 2015)",
      year: 2015,
      url: "https://arxiv.org/abs/1412.6980",
      note: "Introduces Adam, which gives every weight its own step size from running averages of its gradients and suits sparse gradients. It is the kind of optimizer the lesson says would shrink the factored model's edge over rarely updated rows like q.",
    },
    {
      authors: "Ilya Loshchilov and Frank Hutter",
      title: "Decoupled Weight Decay Regularization",
      source: "International Conference on Learning Representations (ICLR 2019)",
      year: 2019,
      url: "https://arxiv.org/abs/1711.05101",
      note: "Introduces AdamW, which applies weight decay separately from Adam's gradient step. It is the optimizer and weight decay that the Toy versus real section says real recipes use instead of this lab's plain SGD.",
    },
    {
      authors: "Ofir Press and Lior Wolf",
      title: "Using the Output Embedding to Improve Language Models",
      source: "Proceedings of the 15th Conference of the European Chapter of the Association for Computational Linguistics (EACL 2017), Volume 2, 157–163",
      year: 2017,
      url: "https://aclanthology.org/E17-2025/",
      note: "Shows that the top weight matrix of a neural language model is itself a word embedding and recommends tying it to the input embedding. It backs the lesson's point that the factored model's two thin matrices are an embedding and an unembedding.",
    },
    {
      authors: "Hugo Touvron, Louis Martin, Kevin Stone, et al.",
      title: "Llama 2: Open Foundation and Fine-Tuned Chat Models",
      source: "arXiv preprint arXiv:2307.09288",
      year: 2023,
      url: "https://arxiv.org/abs/2307.09288",
      note: "Section 2.2 gives the recipe the lesson quotes: AdamW, a cosine schedule with 2,000 warmup steps decaying to 10% of the peak, weight decay 0.1, and gradient clipping at 1.0. Tables 1 and 2 give the 2.0 trillion tokens and GPU hours, and the appendix includes a model card.",
    },
    {
      authors: "Llama Team, AI @ Meta",
      title: "The Llama 3 Herd of Models",
      source: "arXiv preprint arXiv:2407.21783",
      year: 2024,
      url: "https://arxiv.org/abs/2407.21783",
      note: "Table 3 lists a peak learning rate of 3 × 10⁻⁴ for the 8B model, the figure the Toy versus real section compares with this lab's plain-SGD rates. Its pretraining section trains the 405B model with AdamW, a linear warmup, and cosine decay.",
    },
  ],
  checkpoint: [
    {
      prompt:
        "At rank 1 the loss flattens out well above the full-table run, and thirty epochs barely move it. What is the plateau telling you?",
      options: [
        "The learning rate is wrong for rank 1, and a larger one would close the gap with the full table",
        "The corpus is too small for any model to fit, so the full table would plateau just as high",
        "Rank 1 cannot express most of the structure in the data, so longer training cannot reach it",
      ],
      answer: 2,
      explanation:
        "A rank-1 factorization can only express one outer product: every row of scores is the same pattern, scaled or reversed. Most of the bigram structure is unreachable no matter how long it trains. That is an underfitting plateau: more steps do not help, more capacity does. You can check the first option on the Training recipe card: no learning rate, schedule, or clip setting brings rank 1 close to the full table.",
      objective: 1,
    },
    {
      prompt:
        "You switch the corpus from Harbor weather notes to Proverbs and leave Model size and Epochs where they were. Which readout stays the same?",
      options: [
        "The trained weight count, because only Model size sets it",
        "The held-out loss, because the recipe is unchanged",
        "The sample text, because the seed is unchanged",
        "The number of optimizer steps, because the epochs are unchanged",
      ],
      answer: 0,
      explanation:
        "Model size alone sets the weight count, 60 for every unit of rank. The corpus decides the training text and the held-out sentences, so training loss, held-out loss, samples and the step count all follow it. That is why a comparison between runs has to name all four choices: corpus, size, budget and what you report.",
      objective: 0,
    },
    {
      prompt:
        "With the recipe at its defaults, on Proverbs at rank 12 and 30 epochs, training loss keeps falling while held-out loss turns upward. What does that show about the Epochs choice?",
      options: [
        "The held-out text gets harder as training continues, so the two curves cannot be compared",
        "The model is underfitting, so more epochs or a larger rank would close the gap",
        "Both curves score the same sentences, so a rising one must be a plotting error",
        "Past some epoch it fits quirks of its training sentences that do not carry to new text",
      ],
      answer: 3,
      explanation:
        "That is overfitting: held-out loss bottoms out around epoch 18 and climbs back while training loss keeps falling, because later updates fit the particular training sentences rather than structure shared with new text. How long to train is a decision, not a free setting, and the held-out curve is what tells you where to stop.",
      objective: 0,
    },
    {
      prompt: "The model card lists training loss, held-out loss, and perplexity for your run. What does it promise?",
      options: [
        "That the model will score about the same on any other English text, since the card covers the language",
        "How the model scored on sentences it never trained on, for this corpus and recipe, and nothing wider",
        "That the samples shown are a measurement of quality, since they came from the final weights",
        "That the model is safe to use, because a low held-out loss rules out bad behaviour",
      ],
      answer: 1,
      explanation:
        "A model card documents scope: which corpus, which recipe, and how the model scored on text outside its training. It promises nothing about other text, about behaviour such as refusals, or about the samples, which only illustrate the loss. The gap between the two losses is the card's honest half.",
      objective: 2,
    },
    {
      prompt:
        "With the default recipe and 20 epochs on Harbor weather notes, a middle-rank model finishes below the full 900-weight table on both training and held-out loss. What does that show?",
      options: [
        "More weights always fit better, so a result like this must be a plotting error",
        "The factored model can express matrices the full table cannot, so it fits the data more closely",
        "Parameter count is not capacity: shared structure lets each example move more of the model",
        "The held-out split is easier for small models, so the comparison is unfair to the full table",
      ],
      answer: 2,
      explanation:
        "In the full table an example moves only its own 30-weight row. In the factored model it moves its row of the input factor plus the output factor every character shares, so at this data scale each example does more work per weight. The result is conditional on plain SGD, a small corpus and this budget; at real data scale the usual finding runs the other way.",
      objective: 1,
    },
    {
      prompt:
        "You raise Learning rate to 4 and leave the rest of the recipe at its defaults. Constant ends far above Cosine decay at that same peak rate. What is the most likely reason?",
      options: [
        "Cosine shrinks its steps late in the run, so it settles where constant keeps overshooting",
        "Cosine decay makes extra passes over the text, so it has simply trained for more epochs",
        "Constant cannot update the shared output factor, so only a decaying schedule trains both factors",
        "A rate of 4 is too small for a constant schedule to move the weights at all",
      ],
      answer: 0,
      explanation:
        "The two runs read the same text for the same epochs and take the same number of steps; only the step size over time differs. At a peak of 4 a constant step is big enough to overshoot the low point and keeps doing so to the end, while cosine uses the same peak early and then shrinks the step so late updates settle. At the default rate of 0.5 the order reverses and Constant wins, because decaying wastes steps when no step was too large. A schedule has to be judged together with the rate.",
      objective: 3,
    },
    {
      prompt:
        "At Learning rate 8 on the Constant schedule the factored run halts with a diverged loss. You set Gradient clip to 0.50 and change nothing else. What do you expect?",
      options: [
        "It finishes with a finite loss, because any batch gradient above 0.50 is scaled down to that size",
        "It still halts, because clipping only changes the number shown as Peak gradient norm",
        "It matches the default recipe, because clipping cancels out the effect of the larger learning rate",
        "It still halts, because clipping takes effect only after the schedule has decayed the rate",
      ],
      answer: 0,
      explanation:
        "Clipping rescales any batch gradient whose norm exceeds the threshold to exactly that norm, so no step can be longer than the learning rate times 0.50. At rate 8 it fires on nearly every step, 459 of 480, and the run finishes. It still ends well above the default recipe, because clipping contains a step that is too large without making the rate a good one. The full table never needed it: its batch gradient norm cannot exceed the square root of 2, while the factored model multiplies two matrices, so each one's gradient grows with the other and the norm can climb far past that.",
      objective: 3,
    },
    {
      prompt: "You change Batch size from 8 pairs to 64 and leave Epochs at 20. What happens to the run?",
      options: [
        "It takes about eight times fewer steps and ends higher, because the same passes buy fewer updates",
        "It takes the same number of steps, because Epochs alone fixes how many updates the run makes in total",
        "It takes fewer steps but ends lower, because a larger batch always gives a better gradient",
        "It takes more steps, because each larger batch needs extra updates before it is used up",
      ],
      answer: 0,
      explanation:
        "An epoch is one pass over the training pairs, so the step count is the number of pairs divided by the batch size, times the epochs: 960 steps at batch 8 and 120 at batch 64. A bigger batch averages away gradient noise, but with a fixed epoch budget it buys far fewer updates, and at this size the missing updates cost more than the cleaner gradient gains. Batch size and learning rate are chosen together, not one at a time.",
      objective: 3,
    },
    {
      prompt:
        "You switch Training text from Cleaned scrape to Raw scrape and change nothing else. Which readouts move clearly, and which barely move?",
      options: [
        "Steps and Footer lines move clearly while Held out stays close, so held-out loss alone would not flag the junk",
        "Held out rises sharply, because boilerplate and repeats poison every row the held-out sentences rely on, and little else changes",
        "Nothing moves, because both scrapes hold the same training sentences and the same held-out text",
        "The trained weight count rises, because the raw scrape has more characters for the model to store",
      ],
      answer: 0,
      explanation:
        "The raw scrape adds footer lines, two exact repeats, a misspelled copy, and two fragments to the same sentences, so each epoch has more pairs and the run takes more steps. The model learns the footers: its loss on those lines drops by more than half a nat. Held-out loss, which scores different sentences, barely changes and changes sign from seed to seed, so it would not have told you to clean. Cleaning here saves compute and keeps page furniture out of the model rather than lowering the held-out score.",
      objective: 0,
    },
  ],
  initialState,
  Explore,
  serializeState: (state) => JSON.stringify(state),
  hydrateState: (value) => {
    try {
      // The lab trains synchronously on every control change, so a shared link must never be able
      // to request an unbounded run: validate and clamp every field.
      return sanitizeState(JSON.parse(value));
    } catch {
      return sanitizeState(null);
    }
  },
};

export default definition;
